ADAVNCED INDEXING

Indexing - we want to pick specific element from numpy array

In [1]:
import numpy as np

In [6]:
a = np.arange(24).reshape(6,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

There are two types of indexing:
1. Fancy Indexing
2. Boolean Indexing

1. Fancy Indexing

In [7]:
# if we want to print 1,3,and 4th row:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
# 1st row, 3rd row, 4th row and last row:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
# if we want to print 1st column 2nd column and 4th column:
a[:,[0,1,3]] # : -> all rows, [0,1,3] -> means the column we want to select

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

2. Boolean Indexing

In [12]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[95, 22, 90, 24],
       [69, 96, 58, 11],
       [22, 88, 73, 33],
       [42, 62, 83, 25],
       [79, 99, 45, 53],
       [93, 95, 85, 28]], dtype=int32)

In [14]:
# Find all the numbers greater than 50:
a>50 # this will give an boolean array

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
a[a>50]
# This is used to filter data based on certain condition 

array([95, 90, 69, 96, 58, 88, 73, 62, 83, 79, 99, 53, 93, 95, 85],
      dtype=int32)

In [16]:
# FInd all even numbers in array a
a[a%2 == 0]

array([22, 90, 24, 96, 58, 22, 88, 42, 62, 28], dtype=int32)

In [31]:
# find all numbers that are greater than 50 and are evn:
a[(a>50)&(a%2 == 0)]

array([90, 96, 58, 88, 62], dtype=int32)

In [33]:
# Find all numbers Divisible by 7:
a[a%7 == 0]

array([42, 28], dtype=int32)

In [37]:
# find all numbers that are not divisbe by 7:
print(a[a%7 != 0]) # my logic
print(a[~(a%7 == 0)]) # given logic

[95 22 90 24 69 96 58 11 22 88 73 33 62 83 25 79 99 45 53 93 95 85]
[95 22 90 24 69 96 58 11 22 88 73 33 62 83 25 79 99 45 53 93 95 85]


array([95, 22, 90, 24, 69, 96, 58, 11, 22, 88, 73, 33, 62, 83, 25, 79, 99,
       45, 53, 93, 95, 85], dtype=int32)