ADAVNCED INDEXING

Indexing - we want to pick specific element from numpy array

In [1]:
import numpy as np

In [6]:
a = np.arange(24).reshape(6,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

There are two types of indexing:
1. Fancy Indexing
2. Boolean Indexing

1. Fancy Indexing

In [7]:
# if we want to print 1,3,and 4th row:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
# 1st row, 3rd row, 4th row and last row:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
# if we want to print 1st column 2nd column and 4th column:
a[:,[0,1,3]] # : -> all rows, [0,1,3] -> means the column we want to select

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])