BROADCASTING

In [2]:
import numpy as np

In [5]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [7]:
# different shape:

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print("----------------------------------")
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
----------------------------------
[[0 2 4]
 [3 5 7]]
