BROADCASTING

In [2]:
import numpy as np

In [3]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [4]:
# different shape:

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print("----------------------------------")
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
----------------------------------
[[0 2 4]
 [3 5 7]]


Examples based on Broadcasting: 

In [10]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print("Addition of a and b is: ")
c = a + b
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
Addition of a and b is: 
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a+b)

# this will throw an error like (3,4) and (,3) cannot be broadcasted
# (,3) --> (1,3) --> (3,3) ---> (3,4) and (4,3) is not equal so it throws an error

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print()
print(b)
print("Addition of a and b: ")
print(a+b)

# array a(1,3) --> (3,3) and array b(3,1) --> (3,3) here both the arrays are stretched 

[[0 1 2]]

[[0]
 [1]
 [2]]
Addition of a and b: 
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [15]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print()
print(b)
print("Addition of a and b: ")
print(a+b)


# array a(1,3) --> (4,3) 
# array b(4,1) --> (4,3)

[[0 1 2]]

[[0]
 [1]
 [2]
 [3]]
Addition of a and b: 
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.array([1])
b = np.arange(4).reshape(2,2)
print(a)
print()
print(b)
print("Addition of a and b:")
print(a+b)

# here array a(1,1) and array b(2,2) after streching the element of size 1 we get --> a(2,2) and b(2,2)

[1]

[[0 1]
 [2 3]]
Addition of a and b:
[[1 2]
 [3 4]]
