***WORKING WITH MISSING VALUES***

In [1]:
import numpy as np

working with missing values --> np.nan

In [4]:
arr = np.array([1,2,3,4,np.nan,6])
arr

array([ 1.,  2.,  3.,  4., nan,  6.])

In [ ]:
# boolean indexing:

# Step1: Check whetehr there's any missing or nan values in the array or not
np.isnan(arr)

array([False, False, False, False,  True, False])

In [ ]:
# Step2: Take only values:
arr[~np.isnan(arr)] # --> This will remove all the missing values ie. nan values in the array arr '~' -> invert 

array([1., 2., 3., 4., 6.])