1. Write a Python code to import NumPy as np.

In [2]:
import numpy as np

2. Write a Python code to create a NumPy array of integers from 0 to 9.(Using arange function)

In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


3. Write a Python code to create a 3x3 NumPy array with all elements initialized to zero.

In [4]:
b = np.arange(10,19).reshape(3,3)
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


4. Write a Python code to create a 2x2 NumPy array with all elements initialized to one.

In [5]:
c = np.ones((2,2))
c

array([[1., 1.],
       [1., 1.]])

5. Write a Python code to create a NumPy array with the values 1, 3, 5, 7, 9.

In [6]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

6. Write a Python code to create a NumPy array of 10 random integers between 1 and 100.

In [7]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [8]:
b = np.random.random_integers(1,100,10)
b

/tmp/ipykernel_49494/2067075102.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  b = np.random.random_integers(1,100,10)


array([ 9, 96, 21,  8, 17, 35, 11, 95, 39, 39])

7. Write a Python code to add two NumPy arrays element-wise.

In [9]:
a = np.arange(1,10)
b = np.arange(11,20)
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

8. Write a Python code to multiply two NumPy arrays element-wise.

In [10]:
a = np.arange(2,9)
print(a)
print("The value of A after getting multiplied by 3 is: ",a*3)

[2 3 4 5 6 7 8]
The value of A after getting multiplied by 3 is:  [ 6  9 12 15 18 21 24]


9. Write a Python code to perform matrix multiplication using NumPy.

In [11]:
m = np.arange(3,12).reshape(3,3)
n = np.arange(1,10).reshape(3,3)
print("After Matrix Multiplication:\n", m*n)

After Matrix Multiplication:
 [[ 3  8 15]
 [24 35 48]
 [63 80 99]]


10. Write a Python code to transpose a NumPy array.

In [16]:
o = np.arange(1,10).reshape(3,3)
print("The original Matrix is:")
print(o)
print("The Transpose of the Matrix is:")
print(o.transpose())

The original Matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The Transpose of the Matrix is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


11. Write a Python code to find the maximum value of a NumPy array.

In [13]:
x = np.array([1,2,5,7,8])
print("The maximum value in X is:",max(x))

The maximum value in X is: 8


12. Write a Python code to find the minimum value of a NumPy array.

In [14]:
x = np.array([1,2,5,7,8])
print("The minimum value in X is:",min(x))

The minimum value in X is: 1


13. Write a Python code to find the mean, median, and standard deviation of a NumPy array.

In [15]:
x = np.array([1,2,5,7,8])
print(f"The mean of X is: {np.mean(x)}")
print(f"The median of X is {np.median(x)}")
print(f"The standard deviation of X is {np.std(x)}")

The mean of X is: 4.6
The median of X is 5.0
The standard deviation of X is 2.727636339397171


14. Write a Python code to reshape a NumPy array from a 1D array to a 2D array with 2 rows.

In [17]:
y = np.arange(1,10).reshape(3,3)
print("The 2D array is:")
print(y)

The 2D array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


15. Write a Python code to concatenate two NumPy arrays horizontally.

In [22]:
h = np.arange(1,10).reshape(3,3)
i = np.arange(11,20).reshape(3,3)

print("Concatination using concatenate() function: ")
print(np.concatenate((h,i),axis = 1))
print("The horizontal concatenation of h and i is:")
print(np.hstack((h,i)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
The horizontal concatenation of h and i is:
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


16. Write a Python code to concatenate two NumPy arrays vertically.

In [23]:
h = np.arange(1,10).reshape(3,3)
i = np.arange(11,20).reshape(3,3)

print("Concatination using concatenate() function: ")
print(np.concatenate((h,i),axis = 0))
print("The vertical concatenation of h and i is:")
print(np.vstack((h,i)))

Concatination using concatenate() function: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
The vertical concatenation of h and i is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


17. Write a Python code to apply the sine function to each element of a NumPy array.

In [26]:
j = np.arange(1,10).reshape(3,3)
print("The original array is:")
print(j)
print("The sine value of j is:")
print(np.sin(j))

The original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The sine value of j is:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


18. Write a Python code to slice a NumPy array from index 1 to index 5.

In [28]:
k = np.arange(1,10)
print(k[:6])

[1 2 3 4 5 6]


19. Write a Python code to find the unique elements of a NumPy array.

In [30]:
l = np.array([1,2,3,4,3,2,1])
print(f"The unique elements in array {l} is {np.unique(l)}")

The unique elements in array [1 2 3 4 3 2 1] is [1 2 3 4]


20. Write a Python code to sort a NumPy array in ascending order.

In [32]:
z = np.array([9,8,7,6,4,7,2,6,2])
print(f"The sorted array of {z} is {np.sort(z)}")

The sorted array of [9 8 7 6 4 7 2 6 2] is [2 2 4 6 6 7 7 8 9]
