NUMPY FUNDAMENTALS: https://www.youtube.com/live/XF6DCrNTzug?si=Nr88jipeTJKso-2H

Creating NumPy Arrays using "array()" function

In [ ]:
import numpy as np

In [ ]:
# to Create an numpy array:

a = np.array([1,2,3]) # -- this is an 1d array
print(a)

# How to find that its datatype is numpy array?
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [12]:
# How to create an 2D and 3D numpy array?

# -- 2D array
b = np.array([[1,2,3],[4,5,6]])
print("2D Array:")
print(b)

print("-----------------------------------------")

# -- 3D array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,7,6]]])
print("3D Array: ")
print(c)


2D Array:
[[1 2 3]
 [4 5 6]]
-----------------------------------------
3D Array: 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 7 6]]]


DataTypes in NumPY arrays

In [18]:
# dtype function for creating float array
d = np.array([1,2,3],dtype = float)
print(d) # the array formed here is float

print("----------------------------")

e = np.array([1,2,3],dtype = bool)
print(e)
# here 1,2,3,4.. -- is given True value and 0 -- is given False value

print("----------------------------")
f = np.array([1,2,3],dtype = complex)
print(f)



[1. 2. 3.]
----------------------------
[ True  True  True]
----------------------------
[1.+0.j 2.+0.j 3.+0.j]


Array Creation using "arange()" function

In [23]:
g = np.arange(1,11)
print(g)

print("----------------------------")

h = np.arange(1,11,2)
print(h,"-- here we provided steps") # here we provide steps

[ 1  2  3  4  5  6  7  8  9 10]
----------------------------
[1 3 5 7 9] -- here we provided steps


Creating and reshaping Array using "reshape()" function 

In [28]:
i = np.arange(1,11).reshape(2,5)
print(i)

print("----------------------------")

j = np.arange(1,13).reshape(3,4)
print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
----------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
# np.ones and np.zeros
k = np.ones((1,11))
print(k,"-- array consists of all 1s")

print("----------------------------")

l = np.zeros((1,11))
print(l,"-- array consists of all zeros")

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] -- array consists of all 1s
----------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] -- array consists of all zeros
