ARRAY ATTRIBUTES

In [1]:
import numpy as np

In [3]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print("----------------------------------------")
print(a2)
print("----------------------------------------")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
----------------------------------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------------------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# to find number of dimensions using ndim()

print(a1.ndim) # -- 1D array
print(a2.ndim) # -- 2D matrix
print(a3.ndim) # --3D tensor 

1
2
3


In [ ]:
# tells how many dimensions in every array

print(a1.shape) # -- 1 direction has 10 items
print(a2.shape) # -- 3rows and 4 cols
print(a3.shape) # -- (2,2,2) 2--> no. of arrays, 2 --> no.of rows of each array, 2 --> no of cols of each array

(10,)
(3, 4)
(2, 2, 2)


In [10]:
# Size --> tells number of items 
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8
