ARRAY ATTRIBUTES

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print("----------------------------------------")
print(a2)
print("----------------------------------------")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
----------------------------------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------------------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
# to find number of dimensions using ndim()

print(a1.ndim) # -- 1D array
print(a2.ndim) # -- 2D matrix
print(a3.ndim) # --3D tensor 

1
2
3


In [4]:
# tells how many dimensions in every array

print(a1.shape) # -- 1 direction has 10 items
print(a2.shape) # -- 3rows and 4 cols
print(a3.shape) # -- (2,2,2) 2--> no. of arrays, 2 --> no.of rows of each array, 2 --> no of cols of each array

(10,)
(3, 4)
(2, 2, 2)


In [5]:
# Size --> tells number of items 
print(a1.size) # 10 --> that is we have 8 elements
print(a2.size) # 12 --> that is we have 12 elements
print(a3.size) # 8 --> here we have 8 elements 
# NOte: basically this is the multiplication of shape ie (2x2x2)

10
12
8


In [ ]:
# itemsize --> tells the size of item occupied in memory
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

# Note: if we use a1 = np.arange(10),dtype = np.int32 --> the output will be 4bytes
# if dtype = int32 (output will be 4bytes) and dtype = int64 (output will be 8bytes)

8
8
8


In [12]:
# dtype --> this will tell the datatype of the attributes
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64
