CHANGING DATATYPE

In [2]:
import numpy as np

In [3]:
a1 = np.arange(8).reshape(2,2,2)
print(a1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
a1.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print("---------------------------------")
print(a2)