CHANGING DATATYPE

In [1]:
import numpy as np

In [2]:
a1 = np.arange(8).reshape(2,2,2)
print(a1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
a1.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [6]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print("---------------------------------")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


1. Scalar Operations: 

In [ ]:
print("Multiplication: ")
print(a1*2)
print("---------------------------------")

print("Addition: ")
print(a1+2)
print("---------------------------------")

print("Subtraction: ")
print(a1-2)
print("---------------------------------")

print("Division: ")
print(a1/2)
print("---------------------------------")

print("Modulus:")
print(a1%2)
print("---------------------------------")

print("Exponential: ")
print(a1**2)
print("---------------------------------")


Multiplication: 
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
---------------------------------
Addition: 
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
---------------------------------
Subtraction: 
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
---------------------------------
Division: 
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
---------------------------------
Modulus:
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
---------------------------------
Exponential: 
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


2. Relational Operators

In [ ]:

print("checking if each and every elements in the matrix is greater than 5:")
print(a2>5)
print("---------------------------------")

print(a2>15)
print("---------------------------------")

print(a2 == 15)
print("---------------------------------")


checking if each and every elements in the matrix is greater than 5:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
---------------------------------
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
---------------------------------
[[False False False  True]
 [False False False False]
 [False False False False]]
