CHANGING DATATYPE

In [1]:
import numpy as np

In [2]:
a1 = np.arange(8).reshape(2,2,2)
print(a1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
a1.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print("---------------------------------")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


1. Scalar Operations: 

In [5]:
print("Multiplication: ")
print(a1*2)
print("---------------------------------")

print("Addition: ")
print(a1+2)
print("---------------------------------")

print("Subtraction: ")
print(a1-2)
print("---------------------------------")

print("Division: ")
print(a1/2)
print("---------------------------------")

print("Modulus:")
print(a1%2)
print("---------------------------------")

print("Exponential: ")
print(a1**2)
print("---------------------------------")


Multiplication: 
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
---------------------------------
Addition: 
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
---------------------------------
Subtraction: 
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
---------------------------------
Division: 
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
---------------------------------
Modulus:
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
---------------------------------
Exponential: 
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
---------------------------------


2. Relational Operators

In [6]:

print("checking if each and every elements in the matrix is greater than 5:")
print(a2>5)
print("---------------------------------")

print(a2>15)
print("---------------------------------")

print(a2 == 15)
print("---------------------------------")


checking if each and every elements in the matrix is greater than 5:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
---------------------------------
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
---------------------------------
[[False False False  True]
 [False False False False]
 [False False False False]]
---------------------------------


3. Vector Operations

In [ ]:
print(a1)
print("---------------------------------")
print(a2)
print("---------------------------------")

# Note: -- This opertaions only works when the shapes are same 
print("Addition of Two matrices: ")
print(a1 + a2)

print("---------------------------------")

print("Subtarction of Two matrices: ")
print(a2 - a1)

print("---------------------------------")

print("Multiplication of two matrices: ")
print(a1 * a2)

print("---------------------------------")

print("Division of Two Matrices: ")
print(a1/a2)

print("---------------------------------")

print("Power/ Exponential of two Matrices: ")
print(a1**a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
---------------------------------
Addition of Two matrices: 
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
---------------------------------
Subtarction of Two matrices: 
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
---------------------------------
Multiplication of two matrices: 
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
---------------------------------
Division of Two Matrices: 
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
---------------------------------
Power/ Exponential of two Matrices: 
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   683917330202

ARRAY FUNCTIONS

In [20]:
# -- numpy has a lot of build in functions for every mathematical operations 
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[49. 55.  5.]
 [67. 84. 46.]
 [91. 74. 97.]]


1. Max,Min,Sum,Prod

In [ ]:
print(f"The maximum of a1 is {np.max(a1)}")
print("---------------------------------")
print(f"The Minimum of a1 is {np.min(a1)}")
print("---------------------------------")
print(f"The Sum of a1 is {np.sum(a1)}")
print("---------------------------------")
print(f"The Product of the matrix is {np.prod(a1)}")

The maximum of a1 is 97.0
---------------------------------
The Minimum of a1 is 5.0
---------------------------------
The Sum of a1 is 568.0
---------------------------------
The Product of the matrix is 2278691543528400.0


In [34]:
# we can access the max,min,sum,prod of each row or coloumn
# 0 -> col and 1 -> row
print(f"The maximum of each row is {np.max(a1,axis = 1)}")
print(f"The maximum of each column is {np.max(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The minimum of each row is {np.min(a1,axis = 1)}")
print(f"The minimum of each column is {np.min(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The product of each row is {np.prod(a1,axis = 1)}")
print(f"The product of each column is {np.prod(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Sum of each row is {np.sum(a1,axis = 1)}")
print(f"The Sum of each column is {np.sum(a1,axis = 0)}")




The maximum of each row is [55. 84. 97.]
The maximum of each column is [91. 84. 97.]
-------------------------------------------------------------------
The minimum of each row is [ 5. 46. 74.]
The minimum of each column is [49. 55.  5.]
-------------------------------------------------------------------
The product of each row is [ 13475. 258888. 653198.]
The product of each column is [298753. 341880.  22310.]
-------------------------------------------------------------------
The Sum of each row is [109. 197. 262.]
The Sum of each column is [207. 213. 148.]
