ARRAY FUNCTIONS

In [3]:
import numpy as np

In [4]:
# -- numpy has a lot of build in functions for every mathematical operations 
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[85. 78. 10.]
 [91. 25.  2.]
 [74. 73. 49.]]


1. Max,Min,Sum,Prod

In [6]:
print(f"The maximum of a1 is {np.max(a1)}")
print("---------------------------------")
print(f"The Minimum of a1 is {np.min(a1)}")
print("---------------------------------")
print(f"The Sum of a1 is {np.sum(a1)}")
print("---------------------------------")
print(f"The Product of the matrix is {np.prod(a1)}")

The maximum of a1 is 91.0
---------------------------------
The Minimum of a1 is 2.0
---------------------------------
The Sum of a1 is 487.0
---------------------------------
The Product of the matrix is 79850122170000.0


In [ ]:
# we can access the max,min,sum,prod of each row or coloumn
# 0 -> col and 1 -> row
print(f"The maximum of each row is {np.max(a1,axis = 1)}")
print(f"The maximum of each column is {np.max(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The minimum of each row is {np.min(a1,axis = 1)}")
print(f"The minimum of each column is {np.min(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The product of each row is {np.prod(a1,axis = 1)}")
print(f"The product of each column is {np.prod(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Sum of each row is {np.sum(a1,axis = 1)}")
print(f"The Sum of each column is {np.sum(a1,axis = 0)}")

The maximum of each row is [85. 91. 74.]
The maximum of each column is [91. 78. 49.]
-------------------------------------------------------------------
The minimum of each row is [10.  2. 49.]
The minimum of each column is [74. 25.  2.]
-------------------------------------------------------------------
The product of each row is [ 66300.   4550. 264698.]
The product of each column is [572390. 142350.    980.]
-------------------------------------------------------------------
The Sum of each row is [173. 118. 196.]
The Sum of each column is [250. 176.  61.]
