ARRAY FUNCTIONS

In [3]:
import numpy as np

In [4]:
# -- numpy has a lot of build in functions for every mathematical operations 
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[85. 78. 10.]
 [91. 25.  2.]
 [74. 73. 49.]]


1. Basic Functions(Max,Min,Sum,Prod)

In [6]:
print(f"The maximum of a1 is {np.max(a1)}")
print("---------------------------------")
print(f"The Minimum of a1 is {np.min(a1)}")
print("---------------------------------")
print(f"The Sum of a1 is {np.sum(a1)}")
print("---------------------------------")
print(f"The Product of the matrix is {np.prod(a1)}")

The maximum of a1 is 91.0
---------------------------------
The Minimum of a1 is 2.0
---------------------------------
The Sum of a1 is 487.0
---------------------------------
The Product of the matrix is 79850122170000.0


In [ ]:
# we can access the max,min,sum,prod of each row or coloumn
# 0 -> col and 1 -> row
print(f"The maximum of each row is {np.max(a1,axis = 1)}")
print(f"The maximum of each column is {np.max(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The minimum of each row is {np.min(a1,axis = 1)}")
print(f"The minimum of each column is {np.min(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The product of each row is {np.prod(a1,axis = 1)}")
print(f"The product of each column is {np.prod(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Sum of each row is {np.sum(a1,axis = 1)}")
print(f"The Sum of each column is {np.sum(a1,axis = 0)}")

The maximum of each row is [85. 91. 74.]
The maximum of each column is [91. 78. 49.]
-------------------------------------------------------------------
The minimum of each row is [10.  2. 49.]
The minimum of each column is [74. 25.  2.]
-------------------------------------------------------------------
The product of each row is [ 66300.   4550. 264698.]
The product of each column is [572390. 142350.    980.]
-------------------------------------------------------------------
The Sum of each row is [173. 118. 196.]
The Sum of each column is [250. 176.  61.]


2. Statstical Functions (mean,median,std,var)

In [ ]:
print(f"The mean of the array a1 is {np.mean(a1)}")
print("-------------------------------------------------------------------")
print(f"The median of array a1 is {np.median(a1)}")
print("-------------------------------------------------------------------")
print(f"The Standard Deviations of array a1 is {np.std(a1)}")
print("-------------------------------------------------------------------")
print(f"The Variation of array a1 is {np.var(a1)}")

The mean of the array a1 is 54.111111111111114
-------------------------------------------------------------------
The median of array a1 is 73.0
-------------------------------------------------------------------
The Standard Deviations of array a1 is 31.925066586355143
-------------------------------------------------------------------
The Variation of array a1 is 1019.2098765432097
-------------------------------------------------------------------


In [ ]:
# -- here we have a freedom to select we want row or column
# 0 -> col and 1 -> row
# Mean --> calculates the average 
# Median --> sorts the entire thing array and gives the median values
print(f"The Mean of a1 row-wise is {np.mean(a1,axis = 1)}")
print(f"The Mean of a1 column-wise is {np.mean(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Median of a1 row-wise is {np.median(a1,axis = 1)}")
print(f"The Median of a1 column-wise is {np.median(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Standard Deviation of a1 row-wise is {np.std(a1,axis = 1)}")
print(f"The Standard Deviation of a1 column-wise is {np.std(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Variance of a1 row-wise is {np.var(a1,axis = 1)}")
print(f"The Variance of a1 column-wise is {np.var(a1,axis = 0)}")


The Mean of a1 row-wise is [57.66666667 39.33333333 65.33333333]
The Mean of a1 column-wise is [83.33333333 58.66666667 20.33333333]
-------------------------------------------------------------------
The Median of a1 row-wise is [78. 25. 73.]
The Median of a1 column-wise is [85. 73. 10.]
-------------------------------------------------------------------
The Standard Deviation of a1 row-wise is [33.82635396 37.72119946 11.55662388]
The Standard Deviation of a1 column-wise is [ 7.03957069 23.89328125 20.53181813]
-------------------------------------------------------------------
The Variance of a1 row-wise is [1144.22222222 1422.88888889  133.55555556]
The Variance of a1 column-wise is [ 49.55555556 570.88888889 421.55555556]


3. Trignometric Functions (sin,cos,tan)