Array Slicing and Indexing

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print("--------------------------------------------------")
print(a2)
print("--------------------------------------------------")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


--Indexing--

1. 1D array

In [3]:
# If we want a last element in Python: 
print(a1[-1])

9


In [4]:
# If we want 1st element:
print(a1[0])

0


2. 2D Array

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# print the value '6' from the matrix: 
# [row,column], Row - Horizontal and column - vertical 

print(a2[1,2])

6


In [7]:
# Print '11' from the matrix:
print(a2[2,3])

11


In [8]:
# Print '4' from a2:
print(a2[1,0])

4


3. 3D Array

In [9]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# print '5' from a3 [3d Matrix]:
# 1 -> indicates the in ehich matrix the element is located
# 0 -> row (same as 2d matrix)
# 1 -> column (same as 2d matrix)


print(a3[1,0,1])

5


In [11]:
# print '2' from a3 matrix:
print(a3[0,1,0])

2


In [14]:
# print '0 ' from a3: 
print(a3[0,0,0])

0


In [15]:
# print '6' from a3:
print(a3[1,1,0])

6


--Slicing--

1. 1D Array

In [16]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# print 2,3,4 -- (This is known as slicing)

print(a1[2:5])

[2 3 4]


In [ ]:
# Start : end : strides(steps)

print(a1[2:5:2]) # thus will print alternatives

[2 4]
