Iterating

In [3]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print("--------------------------------------------------")
print(a2)
print("--------------------------------------------------")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


1. 1D Array

In [4]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


2.2D Array

In [11]:
# this fetches a whole row one at a time
for i in a2:
    print(i)
print("---------------------------------")
# if we want to fetch single item from array:
for i in np.nditer(a2):
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
---------------------------------
0
1
2
3
4
5
6
7
8
9
10
11


2. 3D Array

In [12]:
# below code fetches the whole matrix one at a time:
for i in a3:
    print(i)
print("---------------------------------")
# if we want to fetch single element:
for i in np.nditer(a3):
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
---------------------------------
0
1
2
3
4
5
6
7


There are 3 types of Reshaping:
1. Reshape
2. Transpose
3. Ravel

1. Reshape - converts an array into 1d or 2d or 3d or nd arrays 

In [15]:
arr = np.arange(1,13).reshape(4,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr1 = np.arange(27).reshape(3,3,3)
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


2. Transpose - This swithces row to column and column to row 

In [ ]:
print(np.transpose(arr))
print("----------------------------")
print(a2.T) # this also does same function

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
----------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


3. Ravel - This converts any type of array into 1D Array

In [29]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])