In [22]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [23]:
np.shape(a) # shows dimensionality 

(3,)

In [24]:
np.size(a) # shows number of elements 

3

In [25]:
np.dtype[a]

numpy.dtype[array([1, 2, 3])]

In [26]:
b = np.array([(1.2,3,4),(4,5,6)], dtype = int)
b

array([[1, 3, 4],
       [4, 5, 6]])

In [27]:
np.shape(b) # shows dimensionality 

(2, 3)

In [28]:
np.size(b) # shows number of elements 

6

In [29]:
np.dtype[b]

numpy.dtype[array([[1, 3, 4],
       [4, 5, 6]])]

In [30]:
c = np.array([[(1.2,3,4),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)
c

array([[[1.2, 3. , 4. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [31]:
np.shape(c) # shows dimensionality 

(2, 2, 3)

In [32]:
np.size(c)

12

In [33]:
np.dtype[c]

numpy.dtype[array([[[1.2, 3. , 4. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])]

In [34]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1.2,3,4),(4,5,6)], dtype = int)
c = np.array([[(1.2,3,4),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)

In [35]:
a.size

3

In [36]:
a.shape

(3,)

In [37]:
b.size

6

In [38]:
b.shape

(2, 3)

In [39]:
a.ndim

1

In [40]:
b.ndim

2

In [41]:
c.ndim

3

In [42]:
z = np.array

In [43]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
print(np.ones((2,3,4),dtype = np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [45]:
d = np.arange(10,50,1) # start = 10, stop = 50, step = 10
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [46]:
# this creates an array of evenly spaced values(step values)
print(np.linspace(0,2,15))

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


In [47]:
e = np.linspace(0,2,num=50, endpoint = True, retstep=False,dtype=None, axis = 0)
print(e)

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]


In [48]:
f = np.linspace(0,2,num=50, endpoint = False, retstep = True, dtype=None, axis = 0)
print(e)


[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]


In [49]:
g = np.eye(3)
g


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
h = np.full((2,2),7)
h

array([[7, 7],
       [7, 7]])

In [51]:
print(np.random.random((2,2)))

[[0.37366655 0.0107151 ]
 [0.02310657 0.25079452]]


In [52]:
np.random.seed(52)
print(np.random.rand(2,2))

[[0.82311034 0.02611798]
 [0.21077064 0.61842177]]
