ARRAY FUNCTIONS

In [1]:
import numpy as np

In [2]:
# -- numpy has a lot of build in functions for every mathematical operations 
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[76. 87. 15.]
 [28. 18. 96.]
 [96. 12. 47.]]


1. Basic Functions(Max,Min,Sum,Prod)

In [3]:
print(f"The maximum of a1 is {np.max(a1)}")
print("---------------------------------")
print(f"The Minimum of a1 is {np.min(a1)}")
print("---------------------------------")
print(f"The Sum of a1 is {np.sum(a1)}")
print("---------------------------------")
print(f"The Product of the matrix is {np.prod(a1)}")

The maximum of a1 is 96.0
---------------------------------
The Minimum of a1 is 12.0
---------------------------------
The Sum of a1 is 475.0
---------------------------------
The Product of the matrix is 259822172897280.0


In [4]:
# we can access the max,min,sum,prod of each row or coloumn
# 0 -> col and 1 -> row
print(f"The maximum of each row is {np.max(a1,axis = 1)}")
print(f"The maximum of each column is {np.max(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The minimum of each row is {np.min(a1,axis = 1)}")
print(f"The minimum of each column is {np.min(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The product of each row is {np.prod(a1,axis = 1)}")
print(f"The product of each column is {np.prod(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Sum of each row is {np.sum(a1,axis = 1)}")
print(f"The Sum of each column is {np.sum(a1,axis = 0)}")

The maximum of each row is [87. 96. 96.]
The maximum of each column is [96. 87. 96.]
-------------------------------------------------------------------
The minimum of each row is [15. 18. 12.]
The minimum of each column is [28. 12. 15.]
-------------------------------------------------------------------
The product of each row is [99180. 48384. 54144.]
The product of each column is [204288.  18792.  67680.]
-------------------------------------------------------------------
The Sum of each row is [178. 142. 155.]
The Sum of each column is [200. 117. 158.]


2. Statstical Functions (mean,median,std,var)

In [5]:
print(f"The mean of the array a1 is {np.mean(a1)}")
print("-------------------------------------------------------------------")
print(f"The median of array a1 is {np.median(a1)}")
print("-------------------------------------------------------------------")
print(f"The Standard Deviations of array a1 is {np.std(a1)}")
print("-------------------------------------------------------------------")
print(f"The Variation of array a1 is {np.var(a1)}")

The mean of the array a1 is 52.77777777777778
-------------------------------------------------------------------
The median of array a1 is 47.0
-------------------------------------------------------------------
The Standard Deviations of array a1 is 33.982929629048165
-------------------------------------------------------------------
The Variation of array a1 is 1154.8395061728395


In [6]:
# -- here we have a freedom to select we want row or column
# 0 -> col and 1 -> row
# Mean --> calculates the average 
# Median --> sorts the entire thing array and gives the median values
print(f"The Mean of a1 row-wise is {np.mean(a1,axis = 1)}")
print(f"The Mean of a1 column-wise is {np.mean(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Median of a1 row-wise is {np.median(a1,axis = 1)}")
print(f"The Median of a1 column-wise is {np.median(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Standard Deviation of a1 row-wise is {np.std(a1,axis = 1)}")
print(f"The Standard Deviation of a1 column-wise is {np.std(a1,axis = 0)}")
print("-------------------------------------------------------------------")
print(f"The Variance of a1 row-wise is {np.var(a1,axis = 1)}")
print(f"The Variance of a1 column-wise is {np.var(a1,axis = 0)}")


The Mean of a1 row-wise is [59.33333333 47.33333333 51.66666667]
The Mean of a1 column-wise is [66.66666667 39.         52.66666667]
-------------------------------------------------------------------
The Median of a1 row-wise is [76. 28. 47.]
The Median of a1 column-wise is [76. 18. 47.]
-------------------------------------------------------------------
The Standard Deviation of a1 row-wise is [31.668421   34.65384378 34.45125381]
The Standard Deviation of a1 column-wise is [28.53457941 34.02939905 33.30999183]
-------------------------------------------------------------------
The Variance of a1 row-wise is [1002.88888889 1200.88888889 1186.88888889]
The Variance of a1 column-wise is [ 814.22222222 1158.         1109.55555556]


3. Trignometric Functions (sin,cos,tan)

In [9]:
print(f"The sine of array a1 is {np.sin(a1)}")
print("-------------------------------------------------------------------")
print(f"The cos of array a1 is {np.cos(a1)}")
print("-------------------------------------------------------------------")
print(f"The tan value of array a1 is {np.tan(a1)}")


The sine of array a1 is [[ 0.56610764 -0.82181784  0.65028784]
 [ 0.27090579 -0.75098725  0.98358775]
 [ 0.98358775 -0.53657292  0.12357312]]
-------------------------------------------------------------------
The cos of array a1 is [[ 0.82433133  0.56975033 -0.75968791]
 [-0.96260587  0.66031671 -0.18043045]
 [-0.18043045  0.84385396 -0.99233547]]
-------------------------------------------------------------------
The tan value of array a1 is [[ 0.68674769 -1.44241747 -0.8559934 ]
 [-0.2814296  -1.13731371 -5.45134011]
 [-5.45134011 -0.63585993 -0.12452757]]


DOT PRODUCT

In [ ]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print("-------------------------------------------------------------------")
print(a3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
print("The dot product if two matrix is: ")
print(np.dot(a2,a3)) # -- This will be an (3x3) matrix 

The dot product if two matrix is: 
[[114 120 126]
 [378 400 422]
 [642 680 718]]


Log and Exponents

In [17]:
print("The log of each item in a1 matrix is: ")
print(np.log(a1))
print("-------------------------------------------------------------------")
print("The Exponents of each value in a1 matrix are: ")
print(np.exp(a1))

The log of each item in a1 matrix is: 
[[4.33073334 4.46590812 2.7080502 ]
 [3.33220451 2.89037176 4.56434819]
 [4.56434819 2.48490665 3.8501476 ]]
-------------------------------------------------------------------
The Exponents of each value in a1 matrix are: 
[[1.01480039e+33 6.07603023e+37 3.26901737e+06]
 [1.44625706e+12 6.56599691e+07 4.92345829e+41]
 [4.92345829e+41 1.62754791e+05 2.58131289e+20]]


Round, Floor and Ceil

In [21]:
a4 = np.random.random((2,3))*100
print(a4)

[[33.77427696 16.30617107  1.14655316]
 [73.17625854 72.71776324 56.51362834]]


In [ ]:
print(np.round(a4)) # -- round function will give the integer values

[[34. 16.  1.]
 [73. 73. 57.]]


In [ ]:
print(np.floor(a4)) # -- this will give the exact value and ignores everything after pointer even its greater than .5
# eg: the value generated is 6.98..
# --- round will give output as 7 
# --- floor will give output as 6

[[33. 16.  1.]
 [73. 72. 56.]]


In [ ]:
print(np.ceil(a4)) # -- this will give the front value of decimal (never ignores anything after decimal)
# eg: the value generated is 6.12..
# --- round will give output as 6
# --- floor will give output as 6
# --- ceil will give output as 7 

[[34. 17.  2.]
 [74. 73. 57.]]
